# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalizing', models.FloatField()),
                ('detailing', models.FloatField()),
                ('participant', models.FloatField()),
                ('observer', models.FloatField()),
                ('object_oriented', models.FloatField()),
                ('connection_oriented', models.FloatField()),
                ('identifying', models.FloatField()),
                ('resultant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RequiredSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('dichotomy_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultDichotomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pole_1', models.CharField(max_length=255)),
                ('pole_2', models.CharField(max_length=255)),
                ('pole_3', models.CharField(max_length=255)),
                ('pole_4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='requiredskills',
            name='working_position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dichotomy.WorkPosition'),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='result_dichotomy_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dichotomy.ResultDichotomy'),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='working_position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dichotomy.WorkPosition'),
        ),
    ]
