# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dichotomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredskills',
            name='dichotomy_number',
            field=models.IntegerField(null=True),
        ),
    ]
